version: '3.4'
services:
  r2eln-share:
    image: alfresco-share-r2eln:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../r2eln-share-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8888"
      REPO_HOST: r2eln-acs
      REPO_PORT: 8080
    ports:
      - "8180:8080"
      - "9898:8888"
  r2eln-acs:
    image: alfresco-content-services-r2eln:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../r2eln-platform-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8888"
    ports:
      - "8080:8080"
      - "8888:8888"
    volumes:
      - r2eln-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - r2eln-postgres
  r2eln-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    ports:
      - "5555:5432"
    volumes:
      - r2eln-db-volume:/var/lib/postgresql/data
  r2eln-ass:
    image: alfresco/alfresco-search-services:1.2.0
    environment:
      SOLR_ALFRESCO_HOST: r2eln-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: r2eln-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
    ports:
      - "8983:8983"
    volumes:
      - r2eln-ass-volume:/opt/alfresco-search-services/contentstore
      - r2eln-ass-volume:/opt/alfresco-search-services/data
volumes:
  r2eln-acs-volume:
    external: true
  r2eln-db-volume:
    external: true
  r2eln-ass-volume:
    external: true